// Reminder: Modify typemap.dat to customize the header file generated by wsdl2h
/* calc.h
   Generated by wsdl2h 2.8.44 from http://webservices.averittexpress.com/TransitTimeService?wsdl and typemap.dat
   2019-05-06 06:53:48 GMT

   DO NOT INCLUDE THIS FILE DIRECTLY INTO YOUR PROJECT BUILDS
   USE THE soapcpp2-GENERATED SOURCE CODE FILES FOR YOUR PROJECT BUILDS

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

/** @page page_notes Notes

@note HINTS:
 - Run soapcpp2 on calc.h to generate the SOAP/XML processing logic.
   Use soapcpp2 -I to specify paths for #import
   To build with STL, 'stl.h' is imported from 'import' dir in package.
   Use soapcpp2 -j to generate improved proxy and server classes.
   Use soapcpp2 -r to generate a report.
 - Use wsdl2h -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Run Doxygen (www.doxygen.org) on this file to generate documentation.
 - Use wsdl2h -R to generate REST operations.
 - Use wsdl2h -nname to use name as the base namespace prefix instead of 'ns'.
 - Use wsdl2h -Nname for service prefix and produce multiple service bindings
 - Use wsdl2h -d to enable DOM support for xsd:anyType.
 - Use wsdl2h -g to auto-generate readers and writers for root elements.
 - Use wsdl2h -b to auto-generate bi-directional operations (duplex ops).
 - Use wsdl2h -U to map XML names to C++ Unicode identifiers instead of _xNNNN.
 - Use wsdl2h -u to disable the generation of unions.
 - Struct/class members serialized as XML attributes are annotated with a '@'.
 - Struct/class members that have a special role are annotated with a '$'.

@warning
   DO NOT INCLUDE THIS ANNOTATED FILE DIRECTLY IN YOUR PROJECT SOURCE CODE.
   USE THE FILES GENERATED BY soapcpp2 FOR YOUR PROJECT'S SOURCE CODE:
   THE soapStub.h FILE CONTAINS THIS CONTENT WITHOUT ANNOTATIONS.

@copyright LICENSE:
@verbatim
--------------------------------------------------------------------------------
gSOAP XML Web services tools
Copyright (C) 2000-2017, Robert van Engelen, Genivia Inc. All Rights Reserved.
The wsdl2h tool and its generated software are released under the GPL.
This software is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
GPL license.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 2 of the License, or (at your option) any later
version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc., 59 Temple
Place, Suite 330, Boston, MA 02111-1307 USA

Author contact information:
engelen@genivia.com / engelen@acm.org

This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial-use license is available from Genivia, Inc., contact@genivia.com
--------------------------------------------------------------------------------
@endverbatim

*/


//gsoapopt c++,w

/******************************************************************************\
 *                                                                            *
 * Definitions                                                                *
 *   http://webservices.averittexpress.com/TransitTimeService                 *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * $CONTAINER                                                                 *
 *   std::vector                                                              *
 *                                                                            *
\******************************************************************************/

template <class T> class std::vector;

/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/

#import "stl.h"	// enable STL containers when used (option -s removes STL dependency)

/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://webservices.averittexpress.com/TransitTimeService"

*/

#define SOAP_NAMESPACE_OF_ns1	"http://webservices.averittexpress.com/TransitTimeService"
//gsoap ns1   schema namespace:	http://webservices.averittexpress.com/TransitTimeService
//gsoap ns1   schema elementForm:	qualified
//gsoap ns1   schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Built-in Schema Types and Top-Level Elements and Attributes                *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Forward Declarations                                                       *
 *                                                                            *
\******************************************************************************/


//  Forward declaration of class ns1__getTransitTime.
class ns1__getTransitTime;

//  Forward declaration of class ns1__AVTTransitTimeRequest.
class ns1__AVTTransitTimeRequest;

//  Forward declaration of class ns1__getTransitTimeResponse.
class ns1__getTransitTimeResponse;

//  Forward declaration of class ns1__AVTTransitTimeResponse.
class ns1__AVTTransitTimeResponse;


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *                                                                            *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Types and Top-Level Elements and Attributes                         *
 *   http://webservices.averittexpress.com/TransitTimeService                 *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *                                                                            *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Complex Types and Top-Level Elements                                *
 *   http://webservices.averittexpress.com/TransitTimeService                 *
 *                                                                            *
\******************************************************************************/

/// @brief "http://webservices.averittexpress.com/TransitTimeService":getTransitTime is a complexType.
///
/// class ns1__getTransitTime operations:
/// - ns1__getTransitTime* soap_new_ns1__getTransitTime(soap*) allocate and default initialize
/// - ns1__getTransitTime* soap_new_ns1__getTransitTime(soap*, int num) allocate array and default initialize values
/// - ns1__getTransitTime* soap_new_req_ns1__getTransitTime(soap*, ...) allocate, set required members
/// - ns1__getTransitTime* soap_new_set_ns1__getTransitTime(soap*, ...) allocate, set all public members
/// - ns1__getTransitTime::soap_default(soap*) default initialize members
/// - int soap_read_ns1__getTransitTime(soap*, ns1__getTransitTime*) deserialize from a stream
/// - int soap_write_ns1__getTransitTime(soap*, ns1__getTransitTime*) serialize to a stream
/// - ns1__getTransitTime* ns1__getTransitTime::soap_dup(soap*) returns deep copy of ns1__getTransitTime, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - ns1__getTransitTime::soap_del() deep deletes ns1__getTransitTime data members, use only after ns1__getTransitTime::soap_dup(NULL) (use soapcpp2 -Ed)
class ns1__getTransitTime
{ public:
/// Element "arg0" of XSD type "http://webservices.averittexpress.com/TransitTimeService":AVTTransitTimeRequest.
    ns1__AVTTransitTimeRequest*          :arg0                          1;	///< Required element.
/// A handle to the soap struct context that manages this instance when instantiated by a context or NULL otherwise (automatically set).
    struct soap                         *soap                          ;
};

/// @brief "http://webservices.averittexpress.com/TransitTimeService":AVTTransitTimeRequest is a complexType.
///
/// class ns1__AVTTransitTimeRequest operations:
/// - ns1__AVTTransitTimeRequest* soap_new_ns1__AVTTransitTimeRequest(soap*) allocate and default initialize
/// - ns1__AVTTransitTimeRequest* soap_new_ns1__AVTTransitTimeRequest(soap*, int num) allocate array and default initialize values
/// - ns1__AVTTransitTimeRequest* soap_new_req_ns1__AVTTransitTimeRequest(soap*, ...) allocate, set required members
/// - ns1__AVTTransitTimeRequest* soap_new_set_ns1__AVTTransitTimeRequest(soap*, ...) allocate, set all public members
/// - ns1__AVTTransitTimeRequest::soap_default(soap*) default initialize members
/// - int soap_read_ns1__AVTTransitTimeRequest(soap*, ns1__AVTTransitTimeRequest*) deserialize from a stream
/// - int soap_write_ns1__AVTTransitTimeRequest(soap*, ns1__AVTTransitTimeRequest*) serialize to a stream
/// - ns1__AVTTransitTimeRequest* ns1__AVTTransitTimeRequest::soap_dup(soap*) returns deep copy of ns1__AVTTransitTimeRequest, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - ns1__AVTTransitTimeRequest::soap_del() deep deletes ns1__AVTTransitTimeRequest data members, use only after ns1__AVTTransitTimeRequest::soap_dup(NULL) (use soapcpp2 -Ed)
class ns1__AVTTransitTimeRequest
{ public:
/// Element "OriginCity" of XSD type xs:string.
    std::string                          OriginCity                     1;	///< Required element.
/// Element "OriginState" of XSD type xs:string.
    std::string                          OriginState                    1;	///< Required element.
/// Element "OriginZip" of XSD type xs:string.
    std::string                          OriginZip                      1;	///< Required element.
/// Element "DestinationCity" of XSD type xs:string.
    std::string                          DestinationCity                1;	///< Required element.
/// Element "DestinationState" of XSD type xs:string.
    std::string                          DestinationState               1;	///< Required element.
/// Element "DestinationZip" of XSD type xs:string.
    std::string                          DestinationZip                 1;	///< Required element.
/// Element "RequestType" of XSD type xs:string.
    std::string*                         RequestType                    0;	///< Optional element.
/// A handle to the soap struct context that manages this instance when instantiated by a context or NULL otherwise (automatically set).
    struct soap                         *soap                          ;
};

/// @brief "http://webservices.averittexpress.com/TransitTimeService":getTransitTimeResponse is a complexType.
///
/// class ns1__getTransitTimeResponse operations:
/// - ns1__getTransitTimeResponse* soap_new_ns1__getTransitTimeResponse(soap*) allocate and default initialize
/// - ns1__getTransitTimeResponse* soap_new_ns1__getTransitTimeResponse(soap*, int num) allocate array and default initialize values
/// - ns1__getTransitTimeResponse* soap_new_req_ns1__getTransitTimeResponse(soap*, ...) allocate, set required members
/// - ns1__getTransitTimeResponse* soap_new_set_ns1__getTransitTimeResponse(soap*, ...) allocate, set all public members
/// - ns1__getTransitTimeResponse::soap_default(soap*) default initialize members
/// - int soap_read_ns1__getTransitTimeResponse(soap*, ns1__getTransitTimeResponse*) deserialize from a stream
/// - int soap_write_ns1__getTransitTimeResponse(soap*, ns1__getTransitTimeResponse*) serialize to a stream
/// - ns1__getTransitTimeResponse* ns1__getTransitTimeResponse::soap_dup(soap*) returns deep copy of ns1__getTransitTimeResponse, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - ns1__getTransitTimeResponse::soap_del() deep deletes ns1__getTransitTimeResponse data members, use only after ns1__getTransitTimeResponse::soap_dup(NULL) (use soapcpp2 -Ed)
class ns1__getTransitTimeResponse
{ public:
/// Element "return" of XSD type "http://webservices.averittexpress.com/TransitTimeService":AVTTransitTimeResponse.
    ns1__AVTTransitTimeResponse*         :return_                       1;	///< Required element.
/// A handle to the soap struct context that manages this instance when instantiated by a context or NULL otherwise (automatically set).
    struct soap                         *soap                          ;
};

/// @brief "http://webservices.averittexpress.com/TransitTimeService":AVTTransitTimeResponse is a complexType.
///
/// class ns1__AVTTransitTimeResponse operations:
/// - ns1__AVTTransitTimeResponse* soap_new_ns1__AVTTransitTimeResponse(soap*) allocate and default initialize
/// - ns1__AVTTransitTimeResponse* soap_new_ns1__AVTTransitTimeResponse(soap*, int num) allocate array and default initialize values
/// - ns1__AVTTransitTimeResponse* soap_new_req_ns1__AVTTransitTimeResponse(soap*, ...) allocate, set required members
/// - ns1__AVTTransitTimeResponse* soap_new_set_ns1__AVTTransitTimeResponse(soap*, ...) allocate, set all public members
/// - ns1__AVTTransitTimeResponse::soap_default(soap*) default initialize members
/// - int soap_read_ns1__AVTTransitTimeResponse(soap*, ns1__AVTTransitTimeResponse*) deserialize from a stream
/// - int soap_write_ns1__AVTTransitTimeResponse(soap*, ns1__AVTTransitTimeResponse*) serialize to a stream
/// - ns1__AVTTransitTimeResponse* ns1__AVTTransitTimeResponse::soap_dup(soap*) returns deep copy of ns1__AVTTransitTimeResponse, copies the (cyclic) graph structure when a context is provided, or (cycle-pruned) tree structure with soap_set_mode(soap, SOAP_XML_TREE) (use soapcpp2 -Ec)
/// - ns1__AVTTransitTimeResponse::soap_del() deep deletes ns1__AVTTransitTimeResponse data members, use only after ns1__AVTTransitTimeResponse::soap_dup(NULL) (use soapcpp2 -Ed)
class ns1__AVTTransitTimeResponse
{ public:
/// Element "OrigCity" of XSD type xs:string.
    std::string*                         OrigCity                       0;	///< Optional element.
/// Element "OrigState" of XSD type xs:string.
    std::string*                         OrigState                      0;	///< Optional element.
/// Element "OrigZip" of XSD type xs:string.
    std::string*                         OrigZip                        0;	///< Optional element.
/// Element "origServiceCenter" of XSD type xs:string.
    std::string*                         origServiceCenter              0;	///< Optional element.
/// Element "DestCity" of XSD type xs:string.
    std::string*                         DestCity                       0;	///< Optional element.
/// Element "DestState" of XSD type xs:string.
    std::string*                         DestState                      0;	///< Optional element.
/// Element "DestZip" of XSD type xs:string.
    std::string*                         DestZip                        0;	///< Optional element.
/// Element "destServiceCenter" of XSD type xs:string.
    std::string*                         destServiceCenter              0;	///< Optional element.
/// Element "directShipment" of XSD type xs:string.
    std::string*                         directShipment                 0;	///< Optional element.
/// Element "EstimatedDays" of XSD type xs:string.
    std::string*                         EstimatedDays                  0;	///< Optional element.
/// Element "EstimatedDeliveryDate" of XSD type xs:string.
    std::string*                         EstimatedDeliveryDate          0;	///< Optional element.
/// Element "Comment" of XSD type xs:string.
    std::string*                         Comment                        0;	///< Optional element.
/// Element "Error" of XSD type xs:string.
    std::string*                         Error                          0;	///< Optional element.
/// A handle to the soap struct context that manages this instance when instantiated by a context or NULL otherwise (automatically set).
    struct soap                         *soap                          ;
};


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *                                                                            *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *                                                                            *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Elements                                              *
 *   http://webservices.averittexpress.com/TransitTimeService                 *
 *                                                                            *
\******************************************************************************/

/// @brief Top-level root element "http://webservices.averittexpress.com/TransitTimeService":AVTTransitTimeRequest of XSD type "http://webservices.averittexpress.com/TransitTimeService":AVTTransitTimeRequest.
/// @note Use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// @brief Top-level root element "http://webservices.averittexpress.com/TransitTimeService":AVTTransitTimeResponse of XSD type "http://webservices.averittexpress.com/TransitTimeService":AVTTransitTimeResponse.
/// @note Use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// @brief Top-level root element "http://webservices.averittexpress.com/TransitTimeService":getTransitTime of XSD type "http://webservices.averittexpress.com/TransitTimeService":getTransitTime.
/// @note Use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.

/// @brief Top-level root element "http://webservices.averittexpress.com/TransitTimeService":getTransitTimeResponse of XSD type "http://webservices.averittexpress.com/TransitTimeService":getTransitTimeResponse.
/// @note Use wsdl2h option -g to auto-generate a top-level root element declaration and processing code.


/******************************************************************************\
 *                                                                            *
 * Additional Top-Level Attributes                                            *
 *   http://webservices.averittexpress.com/TransitTimeService                 *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns1  service name:	TransitTimePortBinding 
//gsoap ns1  service type:	TransitTime 
//gsoap ns1  service port:	http://webservices.averittexpress.com:80/TransitTimeService 
//gsoap ns1  service namespace:	http://webservices.averittexpress.com/TransitTimeService 
//gsoap ns1  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage TransitTimeService Definitions

@section TransitTimeService_bindings Service Bindings

  - @ref TransitTimePortBinding

@section TransitTimeService_more More Information

  - @ref page_notes "Notes"

  - @ref page_XMLDataBinding "XML Data Binding"

  - @ref SOAP_ENV__Header "SOAP Header Content" (when applicable)

  - @ref SOAP_ENV__Detail "SOAP Fault Detail Content" (when applicable)


*/

/**

@page TransitTimePortBinding Binding "TransitTimePortBinding"

@section TransitTimePortBinding_operations Operations of Binding "TransitTimePortBinding"

  - @ref __ns1__getTransitTime

@section TransitTimePortBinding_ports Default endpoints of Binding "TransitTimePortBinding"

  - http://webservices.averittexpress.com:80/TransitTimeService

@note Use wsdl2h option -Nname to change the service binding prefix name


*/

/******************************************************************************\
 *                                                                            *
 * Service Binding                                                            *
 *   TransitTimePortBinding                                                   *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operation                                                          *
 *   __ns1__getTransitTime                                                    *
 *                                                                            *
\******************************************************************************/


/** Operation "__ns1__getTransitTime" of service binding "TransitTimePortBinding".

  - SOAP document/literal style messaging

  - Default endpoints:
    - http://webservices.averittexpress.com:80/TransitTimeService

  - Addressing input action: "http://webservices.averittexpress.com/TransitTimeService/TransitTime/getTransitTimeRequest"

  - Addressing output action: "http://webservices.averittexpress.com/TransitTimeService/TransitTime/getTransitTimeResponse"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call___ns1__getTransitTime(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // input parameters:
    ns1__getTransitTime*                ns1__getTransitTime_,
    // output parameters:
    ns1__getTransitTimeResponse        &ns1__getTransitTimeResponse_
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int __ns1__getTransitTime(
    struct soap *soap,
    // input parameters:
    ns1__getTransitTime*                ns1__getTransitTime_,
    // output parameters:
    ns1__getTransitTimeResponse        &ns1__getTransitTimeResponse_
  );
@endcode

C++ proxy class (defined in soapTransitTimePortBindingProxy.h generated with soapcpp2):
@code
  class TransitTimePortBindingProxy;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use proxy classes;

C++ service class (defined in soapTransitTimePortBindingService.h generated with soapcpp2):
@code
  class TransitTimePortBindingService;
@endcode
Important: use soapcpp2 option '-j' (or '-i') to generate improved and easy-to-use service classes;

*/

//gsoap ns1  service method-protocol:	getTransitTime SOAP
//gsoap ns1  service method-style:	getTransitTime document
//gsoap ns1  service method-encoding:	getTransitTime literal
//gsoap ns1  service method-input-action:	getTransitTime http://webservices.averittexpress.com/TransitTimeService/TransitTime/getTransitTimeRequest
//gsoap ns1  service method-output-action:	getTransitTime http://webservices.averittexpress.com/TransitTimeService/TransitTime/getTransitTimeResponse
int __ns1__getTransitTime(
    ns1__getTransitTime*                ns1__getTransitTime_,	///< Input parameter
    ns1__getTransitTimeResponse        &ns1__getTransitTimeResponse_	///< Output parameter
);

/**

@page TransitTimePortBinding Binding "TransitTimePortBinding"

@section TransitTimePortBinding_policy_enablers Policy Enablers of Binding "TransitTimePortBinding"

None specified.

*/

/******************************************************************************\
 *                                                                            *
 * XML Data Binding                                                           *
 *                                                                            *
\******************************************************************************/


/**

@page page_XMLDataBinding XML Data Binding

SOAP/XML services use data bindings contractually bound by WSDL and auto-
generated by wsdl2h and soapcpp2 (see Service Bindings). Plain data bindings
are adopted from XML schemas as part of the WSDL types section or when running
wsdl2h on a set of schemas to produce non-SOAP-based XML data bindings.

The following readers and writers are C/C++ data type (de)serializers auto-
generated by wsdl2h and soapcpp2. Run soapcpp2 on this file to generate the
(de)serialization code, which is stored in soapC.c[pp]. Include "soapH.h" in
your code to import these data type and function declarations. Only use the
soapcpp2-generated files in your project build. Do not include the wsdl2h-
generated .h file in your code.

Data can be read and deserialized from:
  - an int file descriptor, using soap->recvfd = fd
  - a socket, using soap->socket = (int)...
  - a C++ stream (istream, stringstream), using soap->is = (istream*)...
  - a C string, using soap->is = (const char*)...
  - any input, using the soap->frecv() callback

Data can be serialized and written to:
  - an int file descriptor, using soap->sendfd = (int)...
  - a socket, using soap->socket = (int)...
  - a C++ stream (ostream, stringstream), using soap->os = (ostream*)...
  - a C string, using soap->os = (const char**)...
  - any output, using the soap->fsend() callback

The following options are available for (de)serialization control:
  - soap->encodingStyle = NULL; to remove SOAP 1.1/1.2 encodingStyle
  - soap_mode(soap, SOAP_XML_TREE); XML without id-ref (no cycles!)
  - soap_mode(soap, SOAP_XML_GRAPH); XML with id-ref (including cycles)
  - soap_set_namespaces(soap, struct Namespace *nsmap); to set xmlns bindings


@section  Top-level root elements of schema ""

@section ns1 Top-level root elements of schema "http://webservices.averittexpress.com/TransitTimeService"

  - <ns1:AVTTransitTimeRequest> (use wsdl2h option -g to auto-generate type _ns1__AVTTransitTimeRequest)

  - <ns1:AVTTransitTimeResponse> (use wsdl2h option -g to auto-generate type _ns1__AVTTransitTimeResponse)

  - <ns1:getTransitTime> (use wsdl2h option -g to auto-generate type _ns1__getTransitTime)

  - <ns1:getTransitTimeResponse> (use wsdl2h option -g to auto-generate type _ns1__getTransitTimeResponse)

*/

/* End of calc.h */
